name: Update docs
on:
  workflow_dispatch:
  push:
    paths:
      - filters/**
      - yt-neuter.txt

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          mkdir -p docs/filters
          node docs/gendocs.js
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Automated docs update" 2>&1 && git push